### ISSUE TITLE
Fluent dot attributes for custom prototypes

### ISSUE THREAD

**Issue by Macoron** [space-wizards/RobustToolbox#2788]
Right now localized prototype looks like this:
```yml
- type: reagent
  id: Ephedrine
  name: reagent-name-ephedrine
  desc: reagent-desc-ephedrine
  physicalDesc: reagent-physical-desc-powdery
```

It's painful to work with. We can replace it by fluent dot attributes like it's done for entity prototypes:
```
reagent-ephedrine = ephedrine
        .desc = Increases stun resistance and movement speed, giving you hand cramps. Overdose deals toxin damage and inhibits breathing.
        .physical-desc = {reagent-physical-desc-odorless}
```
