### ISSUE TITLE
PrototypeManager.LoadFromDocument can't actually catch duplicate entities during startup.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/RobustToolbox#3375]
https://github.com/space-wizards/RobustToolbox/blob/9aebaa37495874bc030fa6c9fa4337f5989a5795/Robust.Shared/Prototypes/PrototypeManager.cs#L789-L792

`_prototypes` is properly initialized here, but during startup it's still totally empty so this doesn't actually catch duplicate entries. Both hot-reloading and `loadprototype` set `overwrite` to `true`, avoiding the issue.

You can check content for the following entity and see it's duplicated in the file.

```yml
- type: entity
  parent: SurveillanceCameraBase
  id: SurveillanceCameraScience
```
