### ISSUE TITLE
CVar config number cast issue

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#3788]
A certain CVar was a float type, config specified it with an int instead. The live servers then proceeded to die violently. 

A config like this
```toml
[netres]
limit = 10
```

instead of this
```toml
[netres]
limit = 10.0
```
should not crash.

`unhandled: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Single'.`
