### ISSUE TITLE
UI can memory leak with specific setup

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3828]
Ask rain about it.

**Comment by Just-a-Unity-Dev** [comment]
i have 8gb (windows says 6.9 but physically 8gb) of ram and had my ui header in my client_config.toml looking like this
```toml
[ui]
layout = "Separated"
separated_chat_size = "0.7473958,0"
```
according to dotmem it reached up to 9gb worth of ram usage but i couldn't take a snapshot cause shitty computer
