### ISSUE TITLE
need way to copy and remove components from source to target

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#4484]
## Description
some api to add all of a component registry's components

would be useful for ninja and blob chemicals

add a component registry `abilities` to ninja gloves component:
```
- type: entity
  id: NinjaGloves
  components:
  ...
  - type: NinjaGloves
    abilities:
    - type: StunProvider
    - type: EmagProvider
    - type: BatteryDrainer
    ...
```

```
// in enable gloves
comp.Abilities.CopyComponents(ninja);

// in disable gloves
comp.Abilities.RemoveComponents(ninja);
```

cool api would EnsureComp each component then copy data to it using serializationmanager
removing just remcomp

bonus points if its able to track if the target already had some of the components and to leave them alone, say if wearing emag socks as a ninja then turning gloves off it wouldnt remove emagprovider
