### ISSUE TITLE
system saving idea

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#4856]
i think its good idea to make persistence properly work

have a way to save all systems (registered as DataDefinition) in yml
- MapManager or something has each map -> entity as a datafield (that somehow makes it Serialize instead of just doing mapid -> entity)
- in content wire system stores the round's wire layouts on it so that is datafield

then it can save entities in nullspace (station entities!!!, original body when polymorphed) and stop breaking a lot of things

would also need to support non-systems like MapManager

example yaml

```
- version: 1
  systems:
    MapManager:
      maps:
        0: <insert persistencesave for nullspace here, which stores station entity>
        1: <insert persistencesave for some map here, which no longer has invalid for station>
    Wires:
      layouts:
        highsecorsomething: <WireLayout data for this round>
```

idk if there is anything in place like this and if there is how much of this usecase is supported but it would allow proper persistence
